[package]
name = "blockchain-rust"
version = "0.1.0"
authors = ["skull322@protonmail.com"]
edition = "block-start"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.3.2"
crypto-hash = "0.3.3"
